name: RIBBO
channels:
  - defaults
  - conda-forge
  - huggingface
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anyio=4.13.0
  - aws-c-auth=0.10.1
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.2
  - aws-c-event-stream=0.6.0
  - aws-c-http=0.10.12
  - aws-c-io=0.26.3
  - aws-c-mqtt=0.15.2
  - aws-c-s3=0.11.5
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.10
  - aws-crt-cpp=0.37.4
  - aws-sdk-cpp=1.11.747
  - azure-core-cpp=1.16.2
  - azure-identity-cpp=1.13.3
  - azure-storage-blobs-cpp=12.16.0
  - azure-storage-common-cpp=12.12.0
  - azure-storage-files-datalake-cpp=12.14.0
  - backports.zstd=1.3.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.3.19
  - certifi=2026.2.25
  - charset-normalizer=3.4.7
  - dataclasses=0.8
  - dill=0.4.1
  - exceptiongroup=1.3.1
  - filelock=3.25.2
  - gflags=2.2.2
  - glog=0.7.1
  - h11=0.16.0
  - h2=4.3.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - huggingface_hub=0.29.2
  - hyperframe=6.1.0
  - idna=3.11
  - keyutils=1.6.3
  - krb5=1.22.2
  - ld_impl_linux-64=2.44
  - libabseil=20260107.1
  - libarrow=23.0.1
  - libarrow-acero=23.0.1
  - libarrow-compute=23.0.1
  - libarrow-dataset=23.0.1
  - libarrow-substrait=23.0.1
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcrc32c=1.1.2
  - libcurl=8.19.0
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.5
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libgoogle-cloud=3.3.0
  - libgoogle-cloud-storage=3.3.0
  - libgrpc=1.78.1
  - libiconv=1.18
  - liblapack=3.11.0
  - liblzma=5.8.2
  - libnghttp2=1.68.1
  - libnsl=2.0.0
  - libopenblas=0.3.32
  - libopentelemetry-cpp=1.25.0
  - libopentelemetry-cpp-headers=1.25.0
  - libparquet=23.0.1
  - libprotobuf=6.33.5
  - libre2-11=2025.11.05
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libthrift=0.22.0
  - libutf8proc=2.11.3
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libxml2=2.15.2
  - libxml2-16=2.15.2
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - multiprocess=0.70.19
  - ncurses=6.5
  - nlohmann_json=3.12.0
  - openssl=3.6.1
  - orc=2.3.0
  - packaging=26.0
  - pandas=2.3.3
  - pip=26.0.1
  - prometheus-cpp=1.3.0
  - pthread-stubs=0.3
  - pyarrow-core=23.0.1
  - pysocks=1.7.1
  - python=3.10.20
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.3
  - python-xxhash=3.6.0
  - python_abi=3.10
  - pytz=2026.1.post1
  - pyyaml=6.0.3
  - re2=2025.11.05
  - readline=8.3
  - requests=2.33.1
  - s2n=1.7.1
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - sqlite=3.51.2
  - tk=8.6.15
  - tqdm=4.67.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - urllib3=2.6.3
  - wheel=0.46.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xxhash=0.8.3
  - xz=5.8.2
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.4.0
      - aiofiles==25.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.5
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - async-timeout==5.0.1
      - attrs==23.1.0
      - botorch==0.9.4
      - cffi==2.0.0
      - chex==0.1.90
      - clarabel==0.11.1
      - click==8.3.1
      - cloudpickle==3.1.2
      - cma==4.4.4
      - cmake==4.3.1
      - contourpy==1.3.2
      - cvxpy==1.7.5
      - cycler==0.12.1
      - datasets==4.8.4
      - decorator==5.2.1
      - dm-tree==0.1.10
      - equinox==0.13.8
      - etils==1.13.0
      - evojax==0.2.17
      - flax==0.10.7
      - fonttools==4.62.1
      - frozenlist==1.8.0
      - fsspec==2026.2.0
      - gast==0.7.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - google-vizier==0.1.24
      - googleapis-common-protos==1.74.0
      - gpytorch==1.11
      - greenlet==3.3.2
      - grpcio==1.80.0
      - grpcio-tools==1.80.0
      - gym==0.24.1
      - gym-notices==0.1.0
      - hf-xet==1.4.3
      - huggingface-hub==1.9.0
      - humanize==4.15.0
      - importlib-resources==7.1.0
      - iniconfig==2.3.0
      - jax==0.6.2
      - jaxlib==0.6.2
      - jaxopt==0.8.5
      - jaxtyping==0.3.7
      - jinja2==3.1.6
      - joblib==1.5.3
      - kiwisolver==1.5.0
      - linear-operator==0.5.1
      - lit==18.1.8
      - markdown==3.10.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.9
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.1
      - multipledispatch==1.0.0
      - networkx==3.4.2
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.29.7
      - nvidia-nvtx-cu11==11.7.91
      - offlinerllib==0.1.1
      - opencv-python==4.13.0.92
      - opt-einsum==3.4.0
      - optax==0.2.8
      - orbax-checkpoint==0.11.39
      - osqp==1.1.1
      - pillow==12.2.0
      - platformdirs==4.9.4
      - pluggy==1.6.0
      - portpicker==1.6.0
      - propcache==0.4.1
      - protobuf==6.33.6
      - psutil==7.2.2
      - pyarrow==23.0.1
      - pycparser==3.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.20.0
      - pyparsing==3.3.2
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pytest==8.4.2
      - rich==14.3.3
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - scs==3.2.11
      - sentry-sdk==2.57.0
      - setuptools==81.0.0
      - shellingham==1.5.4
      - simplejson==4.1.1
      - smmap==5.0.3
      - sqlalchemy==1.4.20
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorstore==0.1.78
      - tfp-nightly==0.26.0.dev20260510
      - threadpoolctl==3.6.0
      - tomli==2.4.1
      - toolz==1.1.0
      - torch==2.0.1
      - treescope==0.1.10
      - triton==2.0.0
      - typeguard==2.13.3
      - typer==0.24.1
      - typing-inspection==0.4.2
      - tzdata==2026.1
      - utilsrl==0.6.3
      - uvloop==0.22.1
      - wadler-lindig==0.1.7
      - wandb==0.25.1
      - werkzeug==3.1.8
      - wrapt==2.1.2
      - xgboost==3.2.0
      - yarl==1.23.0
      - zipp==3.23.1
